# Si existe la variable de entorno la usa (Docker), si no usa el valor local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/web2work?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=web2work.app@gmail.com
spring.mail.password=${MAIL_PASSWORD:smjgyucoubthytih}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true