spring.datasource.url=jdbc:h2:file:./data/web2work

spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=sara
spring.datasource.password=sara123

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console