spring.datasource.url=jdbc:h2:file:./data/web2work

spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=sara
spring.datasource.password=sara123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=web2work.app@gmail.com
spring.mail.password=smjgyucoubthytih

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true